"""Build the corrected external-method report from verified experiment outputs."""
import csv,html,json,datetime
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text())
def table(path,ours=True):
    rows=list(csv.reader(path.open()));out=['<div class="tablewrap"><table><thead><tr>']
    out+=['<th>'+html.escape(x)+'</th>' for x in rows[0]];out+=['</tr></thead><tbody>']
    for row in rows[1:]:
        out+=['<tr'+(' class="ours"' if any('(ours)' in x for x in row) else '')+'>']
        out+=['<td>'+html.escape(x)+'</td>' for x in row];out+=['</tr>']
    return ''.join(out+['</tbody></table></div>'])
def small_table(headers,rows):
    return '<div class="tablewrap"><table><thead><tr>'+''.join('<th>'+html.escape(str(x))+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(x))+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def number(x):return '—' if x is None else f'{x:.2f}'
def main():
    a=read(ROOT/'paper_tables/extended_analysis.json');assert a['all_raw_metrics_recomputed_exactly'] and a['all_60_jobs_matched_across_methods_and_panels']
    m=a['panels']['main']['methods'];pairs=a['panels']['main']['paired_comparisons'];o=m['ours']['aggregate'];g=o['bg']
    v=lambda key:g[key]['mean']
    ranks=sorted(m,key=lambda k:m[k]['aggregate']['bg']['tir_lower_bound_pct']['mean'],reverse=True)
    highest=m[ranks[0]]['metadata']['label'];rank=ranks.index('ours')+1
    ranking_label='按 TIR 保守下界排序' if any(abs(r['aggregate']['bg']['tir_upper_bound_pct']['mean']-r['aggregate']['bg']['tir_lower_bound_pct']['mean'])>1e-8 for r in m.values()) else '按完整 TIR 排序'
    sig=[m[k]['metadata']['label'] for k,p in pairs.items() if p.get('tir_holm_adjusted_p') is not None and p['tir_holm_adjusted_p']<.05 and p['tir_difference_lower_bound']['difference']>0]
    training=[]
    for key in ('td3bc','iql','lom','gfp'):
        p=ROOT/'results'/f'{key}_seed260915';c=read(p/'config.json');done=read(p/'completion.json')
        training.append([key.upper() if key!='td3bc' else 'TD3+BC',c['seed'],c['updates'],c.get('gmm_pretrain_steps',0),c['batch_size'],c['actor_lr'],c['critic_lr'],f"{done['seconds']/60:.2f} min",done['final_checkpoint_sha256'][:16]])
    comparison=[]
    for key,p in pairs.items():
        d=p['tir_difference_lower_bound'];u=p['tir_difference_upper_bound'];tb=p['tbr70_pct'];pv=p.get('tir_holm_adjusted_p')
        delta=f"{d['difference']:+.2f}" if abs(d['difference']-u['difference'])<1e-8 else f"[{d['difference']:+.2f}, {u['difference']:+.2f}]"
        ci=f"[{d['ci95'][0]:+.2f}, {d['ci95'][1]:+.2f}]" if delta[0]!='[' else 'Missing-outcome bounds; see CSV'
        comparison.append([m[key]['metadata']['label'],delta,ci,f"{tb['difference']:+.2f}" if tb else '—',f'{pv:.4f}' if pv is not None else '—',p['test_status']])
    risk=[]
    for key,r in m.items():
        q=r['aggregate'];worst=q['worst_patient_tbr70_pct'];risk.append([r['metadata']['label'],q['hypo_events'],q['prolonged_under54_120min_events'],q['max_hypo_low_minutes'],f"adult#{int(worst[0]):03d}: {worst[1]:.2f}%" if worst else '—',number(q['basal_u_per_observed_day']['mean']),number(q['action_tv_per_observed_day']['mean'])])
    body=f'''<header><div class="eyebrow">RESEARCH REVISION · 2026-09-17 · SEED 260915</div><h1>模型结构与外部方法对比</h1><p class="lede">新增 2025 / 2026 年真实发表方法，完成统一场景与共同动作范围评估。内部改进版本已移出正文外部基线表。</p><nav><a href="#architecture">模型结构</a><a href="#training">训练状态</a><a href="#main">正文大表</a><a href="#statistics">配对统计</a><a href="#risk">风险</a><a href="#native">原生动作</a><a href="#sources">论文依据</a></nav></header>
<main><section class="finding"><h2>本轮结果如何理解</h2><p>共同动作范围下，本方法 BG TIR 为 <b>{v('tir_lower_bound_pct'):.2f}%</b>，TBR&lt;70 为 <b>{v('tbr70_pct'):.2f}%</b>，TBR&lt;54 为 <b>{v('tbr54_pct'):.2f}%</b>，失败 <b>{o['failures']}/60</b>。在这张包含固定参考的 10 行表中，{ranking_label}，本方法排第 {rank}；最高者为 {html.escape(highest)}。</p><p>经过 8 项外部方法比较的 Holm 校正，TIR 显著高于：<b>{html.escape('、'.join(sig)) if sig else '本次没有方法达到该判据'}</b>。这只是特定虚拟队列、场景和单个训练 seed 下的比较；不能据此宣称所有指标最优或算法普遍优越。</p><p><b>收益伴随低糖代价：</b>外部方法中 FQL 的 TIR 最高（89.78%）；本方法提高 7.30 个百分点，但 TBR&lt;70 从 0.66% 升至 1.55%，TBR&lt;54 从 0.25% 升至 0.57%。本方法 TBR&lt;54 是主表最高值，不能称为全面最优。</p><p><b>仍有训练信息混淆：</b>本方法使用了额外仿真配对监督及已有仿真训练编码器，其他离线方法使用 Loop。因此主表是同一评估协议下的控制系统比较，尚不是严格同训练数据的算法优势证明。额外信息在主表以 L+S 标出，没有隐藏在脚注之外。</p></section>
<section id="architecture"><h2>01 / 当前模型结构</h2><img class="architecture" src="figures/architecture_actual.svg" alt="已实现的DSENet与模型式RL结构图"><p class="downloads"><a href="figures/architecture_actual.pdf">论文用矢量 PDF</a><a href="figures/architecture_actual.svg">可编辑 SVG</a><a href="figures/architecture_actual.png">PNG</a><a href="结构与训练状态.md">逐模块说明与源码链接</a></p><p>历史为 72×22，即过去 6 小时、5 分钟一格。DSENet 只读 CGM，有效观测参与 RevIN；全局分支采用双向 gated Mamba，patch/stride=<b>12/3</b>（60/15 分钟）；局部 LoRE 分支读取最近 36 点，patch/stride=<b>2/1</b>（10/5 分钟）。Router/Fusion 输出未来 48 点。四个 patch 参数按验证集固定规则选择，不能把微小选择收益夸大为稳定结论。</p><p>另一条冻结 Transformer 路径读取全部历史特征，输出 256 维上下文。参考校准 MLP 加上因果动作响应模块，将 CGM 预测变为候选动作后的血糖轨迹。旧的血糖、奖励、价值头不参与；没有旧 V 的末端 bootstrap。</p><p>策略为 <b>306→128→7</b> 的小 MLP。训练目标是冻结模型下的期望折扣回报减 0.05 KL；七个计划由保持参考基础率，或某个 80 分钟块 ±0.25 U/h 构成。每次仅执行第一个 5 分钟动作，再重新观察。七个未来计划在当前时刻只有三种实际基础率取值，actor 推理不逐候选计算 Q。</p></section>
<section id="training"><h2>02 / RL 是否已经训练结束</h2><p><b>是：当前版本的预定训练已完成。</b>DSENet 候选均训练 3 epochs，最终所选 P03 使用验证选中的第 1 epoch 权重；参考/响应模块训练 100 epochs；策略 seed 260915 完整遍历 225 位患者、1,653,421 个起点，共 6,580 次更新、1 epoch。策略训练前后环境模型哈希一致，策略参数已改变。</p><p><b>这不等于已经证明收敛或性能达标。</b>既定预算结束是日志事实；单次训练没有覆盖随机种子稳定性，当前个体低糖风险仍未解决。此次新增基线全部按固定预算训练，不根据这 60 个场景再选超参、checkpoint 或丢弃失败方法。</p>{small_table(['新增方法','Seed','RL更新','额外GMM更新','Batch','Actor LR','Q LR','实测训练时间','Checkpoint SHA256前缀'],training)}<p>TD3+BC / IQL / GFP 各 50k 更新；LOM 先 10k GMM、再 50k RL，GMM 随后冻结。BC、ReBRAC、FQL和RL-DITR已训练权重复用。所有时间来自本机实际日志，部分任务并发执行，不能作为算法速度排行榜。完整配置、日志及 SHA256 见证据文件。</p><p>GFP 为按作者 MIT 实现核对的 PyTorch 任务适配；LOM 按论文公式独立实现，保留两阶段和 mode selection。LOM 论文与公开代码的 advantage 基准不一致，本次采用论文中的所选 mode 均值，差异已记录。旧基线保留既有开发选择，新方法采用固定论文参数适配，尚未进行等量的任务超参数搜索。所有算法均有 Loop 状态、奖励、步长和预算适配，不声称复现其原始 D4RL/OGBench 分数。</p></section>
<section id="main"><h2>03 / 正文外部方法大表</h2><p><b>统一设置：</b>10 位已曝光虚拟成人 × 2 个餐食随机种子 × 3 个餐时 bolus 条件（1.0 / 0.8 / 1.2），每方法 60 条三天轨迹；前 6h 预热不计入指标。共同 CGM 传感器、胰岛素泵和已宣布餐食 bolus；策略只能改变基础输注。外部策略输出应用相同的“预热实际基础率 ±0.25 U/h”范围。预热基础率和餐时 bolus 是很强的共同先验，须随表交代。同执行范围仍不等于同策略动作集：本方法即时只有三个离散值，其他策略投影后连续；本方法 actor 显式输入持续 anchor，其余网络仍只输入 72×22 历史（外置投影器共享 anchor）。这些结构差异没有被限幅实验消除。</p><p><b>数值：</b>先在每位患者内平均 6 个场景，再对 10 位患者等权平均。± 为患者间样本 SD，不是训练 seed SD。TIR 方括号为提前终止后的未知结局上下界；其他血糖指标按已观测段计算。L=Loop，L+S=Loop及额外仿真训练信息。Projection=外置动作限幅触发率；本方法的同范围限制已内置，因此 0% 不表示没有动作约束。</p>{table(ROOT/'paper_tables/main_comparison.csv')}<p class="downloads"><a href="paper_tables/main_comparison_compact.tex">正文双栏 LaTeX table*</a><a href="paper_tables/main_comparison.tex">全列 LaTeX</a><a href="paper_tables/main_comparison.csv">完整 CSV</a><a href="configs/comparison_manifest.json">方法与权重清单</a><a href="实验合同.md">评估合同</a></p><p>* RL-DITR 使用最初的 categorical reward/value 连续基础率任务适配权重 R03；未把后来添加模拟、修改目标的 R05/H02 放进此行。原论文是住院 T2D 胰岛素滴定，本任务是成人 T1D 基础输注；这一跨任务适配必须保留脚注。它不是作者原临床试验复现。内部变体仍保留在旧实验记录，供消融和开发审计使用。</p></section>
<section id="statistics"><h2>04 / 与本方法的配对差异</h2><img class="architecture" src="figures/control_comparison.svg" alt="TIR和TBR共同呈现的控制结果对比"><p class="downloads"><a href="figures/control_comparison.pdf">对比图矢量PDF</a></p><p>下表为 ours − comparator，单位为百分点。TIR 用患者聚类 bootstrap 10,000 次；完整结局再计算 1,024 种精确符号翻转检验（假设患者间差值在零假设下符号对称/可交换），8 个外部方法构成固定 Holm 家族。缺失 TIR 的方法不生成真实 TIR 的 p 值；其未完成比较在校正家族中保留。固定基础率参考不进入该家族。置信区间均不覆盖训练 seed 不确定性。</p>{small_table(['Comparator','ΔTIR','95% patient CI','ΔTBR70','TIR Holm p','可检验状态'],comparison)}<p class="downloads"><a href="paper_tables/paired_comparisons.csv">全部差值与区间</a><a href="paper_tables/extended_analysis.json">逐患者统计与原始文件哈希</a></p></section>
<section id="risk"><h2>05 / 低糖与个体风险不能被平均 TIR 掩盖</h2>{small_table(['Method','低糖事件总数','<54持续≥120min事件','最长事件低糖分钟','最差患者TBR70','基础输注量 U/day','动作总变差/day'],risk)}<p>低糖事件须持续至少 15 分钟，恢复按连续 15 分钟 ≥70 mg/dL；最长低糖分钟数与事件跨度不同。&lt;54 mg/dL 属于生化低糖，不能仅由仿真血糖判为需要他人协助的临床严重低血糖。无提前终止也不表示没有低糖风险。</p><p>本方法 adult#009 的患者平均 TBR&lt;70 为 12.39%、TBR&lt;54 为 5.66%，6 次连续低于 54 mg/dL 至少 120 分钟，最长低糖事件累计低糖 380 分钟。若正文只强调平均 TIR 而略去此结果，会误导读者。当前研究证据不能宣称已完成实际患者准入。</p></section>
<section id="native"><h2>06 / 原生动作范围：限制本身贡献了多少</h2><p>这里保留各模型原来的动作支持范围；既有 BC、ReBRAC、FQL、本方法和固定参考的同场景结果直接复用，不重复训练或制造新 seed。对照此表与主表，可以观察共同限幅是否主导收益。该表本身动作支持不同，不能用它独立证明算法优越性。</p>{table(ROOT/'paper_tables/native_comparison.csv')}<p class="downloads"><a href="paper_tables/native_comparison.tex">附表 LaTeX</a><a href="paper_tables/native_comparison.csv">CSV</a><a href="paper_tables/risk_extra.csv">完整风险与输注附表</a></p></section>
<section id="metrics"><h2>07 / 为什么评价不止 TIR、TBR</h2><p>近期领域论文并不只看两个百分比：<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0317662">PPO-AP（2025，Table 2）</a>同时报告风险指数与治疗失败；<a href="https://arxiv.org/html/2604.00385v1">GUIDE（2026预印本，Tables IV/VI）</a>报告 TIR/TBR/TAR/CV 和患者级配对统计；<a href="https://arxiv.org/html/2501.15972v1">PAINT（ECAI 2025 原始稿）</a>还使用 Magni risk。风险公式不同的数值不能混用。本表采用项目冻结的 LBGI/HBGI 实现。</p><p><a href="https://www.nature.com/articles/s41591-023-02552-9">原 RL-DITR</a>临床主要终点是平均每日指尖血糖，并另评 TIR/TBR/TAR/CV。剂量 MAE、PCC 或离线 WIS/ESS 属于不同证据；在没有可靠行为策略概率的连续基础率任务中，不能草率补一个 WIS 数字充实表格。</p><p>预测器也有独立评价：以下为此前已完成的真实 Loop 患者隔离评估，单位 mg/dL。它说明预测误差，不能代替 RL 闭环性能。该小表只有便宜预测参考，并不是最新血糖预测模型的全面 SOTA 对比。</p>{table(ROOT.parent/'paper_tables/forecast_heldout.csv')}<p><a href="metrics_literature.md">完整文献、指标定义、阈值与筛选记录</a></p></section>
<section id="sources"><h2>08 / 方法来源与复现范围</h2><ul>
<li><a href="https://proceedings.neurips.cc/paper_files/paper/2021/file/a8166da05c5a094f7dc03724b41886e5-Paper.pdf">TD3+BC · NeurIPS 2021</a> · <a href="https://github.com/sfujim/TD3_BC">作者代码</a></li>
<li><a href="https://arxiv.org/abs/2110.06169">IQL · ICLR 2022</a> · <a href="https://github.com/ikostrikov/implicit_q_learning">作者代码</a></li>
<li><a href="https://papers.neurips.cc/paper_files/paper/2023/hash/26cce1e512793f2072fd27c391e04652-Abstract-Conference.html">ReBRAC · NeurIPS 2023</a> · <a href="https://github.com/tinkoff-ai/ReBRAC">作者代码</a></li>
<li><a href="https://proceedings.mlr.press/v267/park25f.html">FQL · ICML 2025</a> · <a href="https://github.com/seohongpark/fql">作者代码</a></li>
<li><a href="https://proceedings.iclr.cc/paper_files/paper/2025/hash/be62c4a943675195ff5a2a98d5b9724f-Abstract-Conference.html">LOM · ICLR 2025</a> · <a href="https://github.com/MianchuWang/LOM">作者审阅来源</a>（本次按论文独立实现）</li>
<li><a href="https://proceedings.iclr.cc/paper_files/paper/2026/hash/33f131b806a93d376cf0ce1a456464bb-Abstract-Conference.html">GFP · ICLR 2026</a> · <a href="https://github.com/Simple-Robotics/guided-flow-policy">作者代码</a></li>
<li><a href="https://www.nature.com/articles/s41591-023-02552-9">RL-DITR · Nature Medicine 2023</a>（公开数据连续基础率任务适配）</li></ul><p>另查到 MeanFlowQL（AAAI 2026）和 Value Flows（ICLR 2026），未纳入本轮训练，不能写成复现失败。糖尿病专用 PPO-AP 是在线全输注控制，GUIDE 含进食/bolus动作，不能直接冒充本任务同设置基线；PAINT 本次未核验到完整官方实现。详见<a href="recent_baselines_research.md">近期方法筛选</a>。</p></section>
<section><h2>09 / 验证与仍未解决的要求</h2><p>四个新增方法均通过真实数据 CUDA 有限损失、参数更新、动作范围及保存加载一致性检查。LOM 的分阶段冻结、实际后继动作和 mode 选择经过机制检查。场景生成和仿真函数保持原样；固定基础率三天轨迹与旧记录完全相同。两套表均由同一评分器重算原始轨迹，并核对共同场景、权重以及主表动作范围。</p><p>仍未解决：严格同训练信息的算法比较、多训练 seed 稳定性、未曝光虚拟患者泛化、更长时段和更困难餐食环境、adult#009 低糖问题。此次提供的是可审计的真实对比表与 LaTeX 格式，不保证仅凭这组实验即可被 A 类会议接收。必须随正文保留数据与动作合同，不能删掉限制后声称 SOTA。</p><p class="downloads"><a href="checks/baseline_smoke.json">CUDA 检查</a><a href="checks/evaluator_equivalence.json">评估等价检查</a><a href="paper_tables/extended_analysis.json">逐条结果重算</a><a href="交接与证据.md">交接与证据清单</a></p></section></main><footer>生成时间：{datetime.datetime.now().isoformat(timespec='seconds')} · 不含患者私人资料或远端凭据 · 所有数值来自本项目实际运行</footer>'''
    css='''*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#182d3d;font:15px/1.8 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif}header,main,footer{max-width:1540px;margin:auto}header{padding:54px 42px 32px;background:#17334b;color:white}h1{font-size:38px;margin:8px 0}h2{font-size:23px;margin:0 0 18px;line-height:1.4}.eyebrow{font-size:12px;letter-spacing:2px;color:#aac9e1}.lede{font-size:18px;color:#d8e7f2;max-width:970px}nav{display:flex;gap:20px;flex-wrap:wrap}nav a{color:#d3e9ff}a{color:#176b9a;text-decoration:none}a:hover{text-decoration:underline}main{padding:26px 30px}section{background:white;border:1px solid #dce4e9;border-radius:9px;padding:30px;margin:0 0 24px}.finding{border-left:5px solid #bd7d29}p{margin:13px 0}.architecture{width:100%;height:auto}.downloads{display:flex;gap:24px;flex-wrap:wrap;font-weight:600}.tablewrap{overflow:auto;margin:22px -8px}table{border-collapse:collapse;width:100%;font-size:12px;font-variant-numeric:tabular-nums}th{background:#17334b;color:white;font-weight:600}th,td{padding:11px 10px;border-bottom:1px solid #dbe4ea;text-align:right;white-space:nowrap}th:first-child,td:first-child,th:nth-child(2),td:nth-child(2){text-align:left}tbody tr:nth-child(even){background:#f7f9fb}.ours{background:#e3f2ed!important;font-weight:700}footer{padding:20px 42px 45px;color:#637b8a;font-size:12px}li{margin:6px 0}@media print{@page{size:A3 landscape;margin:14mm}body{background:white;font-size:10pt}header{padding:12px 20px}main{padding:0}h1{font-size:24pt}section{border:0;padding:14px 0;break-inside:auto}h2{break-after:avoid}nav{display:none}.tablewrap{overflow:visible;margin:10px 0}table{font-size:7pt}th,td{padding:5px}.architecture{max-height:230mm}footer{padding:10px 0}a{color:inherit}}'''
    dest=ROOT/'论文正文对比报告.html';dest.write_text('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>模型结构与外部方法对比</title><style>'+css+'</style>'+body+'</html>')
    print(dest)
if __name__=='__main__':main()
