"""Compose learned reference and intervention dynamics with complete weight provenance."""
import copy,hashlib,json
import torch
from ditr_data import ROOT
from ditr_model import DITRAgent

def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()

def main():
 torch.manual_seed(260915);out=ROOT/'results/C01_response_patient_composition';out.mkdir(exist_ok=False)
 encoder_path=ROOT/'results/H02_prefix_sim_factual/patient_best.pt';policy_path=ROOT/'results/H02_prefix_sim_factual/policy_last.pt';gpath=ROOT/'results/P01_conditioned_response_operator/response_last.pt';zpath=ROOT/'results/P03_latent_response_operator/state_response_last.pt'
 encoder=torch.load(encoder_path,map_location='cpu');old=torch.load(policy_path,map_location='cpu');g=torch.load(gpath,map_location='cpu');z=torch.load(zpath,map_location='cpu');assert g['encoder_sha256']==z['encoder_sha256']==sha(encoder_path)
 for name,value in encoder['agent'].items():
  if name.startswith('patient.'):torch.testing.assert_close(value,old['agent'][name],rtol=0,atol=0)
 norm=json.loads((ROOT.parent/'Loop数据集/训练管线_v2/prepared/normalization.json').read_text())['basal_u_prev_5min'];model_cfg=copy.deepcopy(old['config']['model']);model_cfg['response_config']={'conditioned':True,'basal_mean':norm['mean'],'basal_scale':norm['scale'],'reward':'unchanged status function of point glucose forecast; not E[r(G)] under predictive uncertainty'}
 agent=DITRAgent(**model_cfg);agent.patient.background.load_state_dict({k[len('patient.'):]:v for k,v in old['agent'].items() if k.startswith('patient.')});agent.policy.load_state_dict({k[len('policy.'):]:v for k,v in old['agent'].items() if k.startswith('policy.')});agent.patient.glucose_response.load_state_dict(g['model']);agent.patient.state_response.load_state_dict(z['model'])
 cfg=copy.deepcopy(old['config']);cfg.update({'name':'H04_response_patient_rl','model':model_cfg,'stages':['policy'],'initialize_checkpoint':'results/C01_response_patient_composition/patient_composed.pt','patient_training_origin':'H02_prefix_sim_factual','policy_rng_seed':260915,'policy_loss_variant':'bounded_return_nll','selection':'fixed response100epochs without development checkpoint selection; full additional policy epoch; control assessed independently','response_sources':{'glucose':str(gpath.relative_to(ROOT)),'latent':str(zpath.relative_to(ROOT))}});cfg.pop('simulation',None)
 cfg['adaptations']=['fR and reference fT/fP retain full-Loop and matched simulator training from H02; no original data removed','fT decomposes reference trajectory and learned causal convolution responses of glucose and latent state; local conditional linear time-invariance is a testable assumption','response coefficients trained only from same-state paired intervention labels, not confounded factual action correlations','reward uses unchanged status function applied to predicted point glucose, removing independent head inconsistency; nonlinear expected-risk calibration not established','pi initialized from H02 full policy epoch; one additional full Loop policy epoch at same seed with bounded-return NLL objective; matched unchanged-H02 extra-policy control','reference basal reconstructed from last recorded history in original units, never simulator nominal parameters; missing reference is only a coordinate origin, not a fallback dose']
 composed={'agent':agent.state_dict(),'target_patient':agent.patient.state_dict(),'config':cfg,'stage':'patient','step':0,'samples':0,'composition_not_an_optimizer_update':True,'source_patient_step':encoder['step'],'source_policy_step':old['step'],'response_training_steps':3200}
 torch.save(composed,out/'patient_composed.pt');(ROOT/'configs/H04.json').write_text(json.dumps(cfg,indent=2))
 control=copy.deepcopy(old['config']);control.update({'name':'R07_H02_extra_policy_control','stages':['policy'],'initialize_checkpoint':'results/H02_prefix_sim_factual/policy_last.pt','allow_policy_initialization':True,'patient_training_origin':'H02_prefix_sim_factual','policy_rng_seed':260915,'policy_loss_variant':'bounded_return_nll'});control.pop('simulation',None);control['adaptations']=['H02 patient and policy initialization unchanged; same extra full Loop policy epoch as H04, same seed and policy RNG reset; controls additional policy optimization, not response-branch parameter budget'];(ROOT/'configs/R07.json').write_text(json.dumps(control,indent=2))
 manifest={'status':'composed_not_yet_policy_trained_or_control_validated','sources':{str(p.relative_to(ROOT)):sha(p) for p in [encoder_path,policy_path,gpath,zpath]},'shared_encoder_exact_verified':True,'full_Loop_pretraining_retained':True,'patient_parameters':sum(p.numel() for p in agent.patient.parameters()),'policy_parameters':sum(p.numel() for p in agent.policy.parameters()),'checkpoint_sha256':sha(out/'patient_composed.pt'),'model_config':model_cfg,'point_risk_limitation':True};(out/'manifest.json').write_text(json.dumps(manifest,indent=2));print(json.dumps(manifest),flush=True)

if __name__=='__main__':main()
